// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6-OvNprvn52XAyZqzxJjEoWIQI2uIqY4',
    appId: '1:1014955636236:web:950c4ee9505447ba5a2029',
    messagingSenderId: '1014955636236',
    projectId: 'safezone-tcc',
    authDomain: 'safezone-tcc.firebaseapp.com',
    databaseURL: 'https://safezone-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-tcc.firebasestorage.app',
    measurementId: 'G-9XEHNDTYPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQRphlvUFQITyVRA2GvZAQEhF8ra2LjbY',
    appId: '1:1014955636236:android:b6d46ded4e9a1fd65a2029',
    messagingSenderId: '1014955636236',
    projectId: 'safezone-tcc',
    databaseURL: 'https://safezone-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-tcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3DmTY9bG9SUslDZXq4zHY_0kBDMm6vE',
    appId: '1:1014955636236:ios:82d0b1b95e1207645a2029',
    messagingSenderId: '1014955636236',
    projectId: 'safezone-tcc',
    databaseURL: 'https://safezone-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-tcc.firebasestorage.app',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF3DmTY9bG9SUslDZXq4zHY_0kBDMm6vE',
    appId: '1:1014955636236:ios:82d0b1b95e1207645a2029',
    messagingSenderId: '1014955636236',
    projectId: 'safezone-tcc',
    databaseURL: 'https://safezone-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-tcc.firebasestorage.app',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6-OvNprvn52XAyZqzxJjEoWIQI2uIqY4',
    appId: '1:1014955636236:web:ca13b3f4afc362675a2029',
    messagingSenderId: '1014955636236',
    projectId: 'safezone-tcc',
    authDomain: 'safezone-tcc.firebaseapp.com',
    databaseURL: 'https://safezone-tcc-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-tcc.firebasestorage.app',
    measurementId: 'G-4J0TKXX95E',
  );
}
